name: Deploy to Github pages

on:
  push:
    branches:
      - main
    paths:
      - "society-management-ui/**"
      - ".github/workflows/deploy-pages.yml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and Deploy ng application
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: society-management-ui/package-lock.json

      - name: Install npm dependencies
        working-directory: ./society-management-ui
        run: npm ci

      - name: Generate environment.ts
        working-directory: ./society-management-ui
        run: |
          mkdir -p src/environments

          cat > src/environments/environment.ts << EOF
          export const environment = {
            production: true,
            supabaseUrl: '${{ secrets.SUPABASE_URL }}',
            supabaseAnonKey: '${{ secrets.SUPABASE_ANON_KEY }}'
          };
          EOF

      - name: Verify environment file exists
        working-directory: ./society-management-ui
        run: |
          ls -la src/environments

      - name: Build ng application
        working-directory: ./society-management-ui
        run: npm run build:prod

      - name: Execute Unit tests
        working-directory: ./society-management-ui
        run: npm run test --watch=false --browsers=ChromeHeadless

      - name: Configure Language landing page
        working-directory: ./society-management-ui
        run: |
          cp dist/society-management-ui/browser/en-US/html/index.redirect.html \
          dist/society-management-ui/browser/index.html

      - name: Setup Github pages
        uses: actions/configure-pages@v5

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: society-management-ui/dist/society-management-ui/browser

      - name: Deploy to Github pages
        uses: actions/deploy-pages@v4
